version: "3.3"
services:
  bot:
    #image: # TODO SET IMAGE
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      TOKEN: ${TOKEN}
      OWNER: ${OWNER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ADMINS: ${ADMINS}
    volumes:
     # - /srv/hellshade-bot/files:/files
      - ./files:/files
      - ./:/bot
     # - ./alembic:/bot/alembic
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      #- /srv/hellshade-bot/data:/var/lib/postgresql/data/
      - ./data:/var/lib/postgresql/data/

