"""Add message id to GW2DailySub

Revision ID: 0332a7c127a8
Revises: ec623cbb739a
Create Date: 2022-09-04 09:06:39.020308

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = '0332a7c127a8'
down_revision = 'ec623cbb739a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gw2_daily_subs', sa.Column('message_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gw2_daily_subs', 'message_id')
    # ### end Alembic commands ###
