"""Add Private Slash Commands

Revision ID: 586d604e8c75
Revises: aa0eacd9ff7e
Create Date: 2022-02-01 18:12:34.004603

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = '586d604e8c75'
down_revision = 'aa0eacd9ff7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('server_uuid', core.database.types.GUID(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['server_uuid'], ['servers.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commands')
    # ### end Alembic commands ###
