"""Role channel and message

Revision ID: 708cfd660056
Revises: 897609c113a7
Create Date: 2021-03-10 09:52:30.039525

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = '708cfd660056'
down_revision = '897609c113a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('role_channel', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('role_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'role_message')
    op.drop_column('servers', 'role_channel')
    # ### end Alembic commands ###
