"""Add SteamID to player

Revision ID: 7dbc25f27f3e
Revises: 586d604e8c75
Create Date: 2024-04-27 11:09:36.128239

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = '7dbc25f27f3e'
down_revision = '586d604e8c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('steam_id', sa.Integer(), nullable=True))
    op.create_unique_constraint("unique_player_steamid", 'players', ['steam_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_player_steamid", 'players', type_='unique')
    op.drop_column('players', 'steam_id')
    # ### end Alembic commands ###
