"""Add roles

Revision ID: 897609c113a7
Revises: da2e6c874fa4
Create Date: 2021-03-09 09:08:13.112482

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = '897609c113a7'
down_revision = 'da2e6c874fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('member_role_association',
    sa.Column('role_uuid', core.database.types.GUID(), nullable=True),
    sa.Column('member_uuid', core.database.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['member_uuid'], ['members.uuid'], ),
    sa.ForeignKeyConstraint(['role_uuid'], ['roles.uuid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_role_association')
    op.drop_table('roles')
    # ### end Alembic commands ###
