"""Change SteamID to string

Revision ID: 9133ef089841
Revises: a71060d7ecbb
Create Date: 2024-04-27 19:47:28.563633

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = '9133ef089841'
down_revision = 'a71060d7ecbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'steam_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'steam_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
