"""Add Dota Guild

Revision ID: a71060d7ecbb
Revises: 7dbc25f27f3e
Create Date: 2024-04-27 15:33:37.247522

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = 'a71060d7ecbb'
down_revision = '7dbc25f27f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dota_guilds',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('role_discord_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('server_uuid', core.database.types.GUID(), nullable=True),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_uuid'], ['servers.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dota_guilds')
    # ### end Alembic commands ###
