"""Add Guild Wars 2 tables

Revision ID: a916d47c6b60
Revises: 586d604e8c75
Create Date: 2022-08-16 16:31:06.886997

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = 'a916d47c6b60'
down_revision = '586d604e8c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gw2_api_keys',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('player_uuid', core.database.types.GUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('gw2_guilds',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('server_uuid', core.database.types.GUID(), nullable=True),
    sa.Column('guild_gw2_id', sa.String(), nullable=False),
    sa.Column('guild_owner_uuid', core.database.types.GUID(), nullable=True),
    sa.Column('guild_upgrade_channel', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['guild_owner_uuid'], ['players.uuid'], ),
    sa.ForeignKeyConstraint(['server_uuid'], ['servers.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('gw2_guild_upgrades',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gw2_guild_uuid', core.database.types.GUID(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['gw2_guild_uuid'], ['gw2_guilds.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gw2_guild_upgrades')
    op.drop_table('gw2_guilds')
    op.drop_table('gw2_api_keys')
    # ### end Alembic commands ###
