"""Add heartbeat

Revision ID: aa0eacd9ff7e
Revises: c0aee0e983df
Create Date: 2021-07-15 07:58:27.880297

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = 'aa0eacd9ff7e'
down_revision = 'c0aee0e983df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'last_seen')
    # ### end Alembic commands ###
