"""Server relation to roles

Revision ID: b8c50d4e6a0c
Revises: 708cfd660056
Create Date: 2021-03-11 08:44:35.314208

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = 'b8c50d4e6a0c'
down_revision = '708cfd660056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roleemojis',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('role_uuid', core.database.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_uuid'], ['roles.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('role_uuid')
    )
    op.add_column('roles', sa.Column('server_uuid', core.database.types.GUID(), nullable=True))
    op.create_foreign_key(None, 'roles', 'servers', ['server_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'server_uuid')
    op.drop_table('roleemojis')
    # ### end Alembic commands ###
