"""Add GW2 upgrade id field to Gw2GuildUpgrade table

Revision ID: d2efaedb37c3
Revises: a916d47c6b60
Create Date: 2022-08-17 15:56:51.012760

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = 'd2efaedb37c3'
down_revision = 'a916d47c6b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gw2_guild_upgrades', sa.Column('gw2_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gw2_guild_upgrades', 'gw2_id')
    # ### end Alembic commands ###
