"""Init

Revision ID: da2e6c874fa4
Revises: 
Create Date: 2020-11-18 20:00:04.164305

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = 'da2e6c874fa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('title')
    )
    op.create_table('players',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('servers',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('server_exp', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('users',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('members',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('player_uuid', core.database.types.GUID(), nullable=True),
    sa.Column('server_uuid', core.database.types.GUID(), nullable=True),
    sa.Column('level_uuid', core.database.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['level_uuid'], ['levels.uuid'], ),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.uuid'], ),
    sa.ForeignKeyConstraint(['server_uuid'], ['servers.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('users')
    op.drop_table('servers')
    op.drop_table('players')
    op.drop_table('levels')
    # ### end Alembic commands ###
