"""GW2 Daily subscriptions

Revision ID: ec623cbb739a
Revises: d2efaedb37c3
Create Date: 2022-09-03 17:46:07.540567

"""
from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision = 'ec623cbb739a'
down_revision = 'd2efaedb37c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gw2_daily_subs',
    sa.Column('uuid', core.database.types.GUID(), nullable=False),
    sa.Column('server_uuid', core.database.types.GUID(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('daily_type', sa.Enum('PvE', 'PvP', 'WvW', 'Fractals', 'Strikes', 'LivingWorld', name='dailytype'), nullable=False),
    sa.ForeignKeyConstraint(['server_uuid'], ['servers.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gw2_daily_subs')
    # ### end Alembic commands ###
