[project]
name = "hellshade-bot-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Max Mecklin", email = "max@meckl.in" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
core = "core:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
